name: BUILD WAZUH INDEXER VERSION MULTIPLATFORM

on:
  push:
    branches:
      - main
    paths:
      - VERSION
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set Version TAG
        run: echo "WAZUH_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: wazuh-indexer/
          push: true
          tags: |
            kalingth/wazuh-indexer:${{ env.WAZUH_VERSION }}
            kalingth/wazuh-indexer:latest
          platforms: |
            linux/arm64
          build-args: |
            WAZUH_VERSION=${{ env.WAZUH_VERSION }}
            WAZUH_TAG_REVISION=1
